// <auto-generated />
using System;
using ApiProdutosPessoas.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ApiProdutosPessoas.Migrations
{
    [DbContext(typeof(TesteApidbContext))]
    [Migration("20250307203637_InitialDB")]
    partial class InitialDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("ApiProdutosPessoas.Models.MarcaModel", b =>
                {
                    b.Property<int>("CodigoMarca")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Cod_Marca")
                        .UseIdentityColumn();

                    b.Property<string>("DescricaoMarca")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Descricao");

                    b.HasKey("CodigoMarca");

                    b.ToTable("Marcas");
                });

            modelBuilder.Entity("ApiProdutosPessoas.Models.ProdutoModel", b =>
                {
                    b.Property<int>("Codigo")
                        .HasColumnType("int")
                        .HasColumnName("Codigo");

                    b.Property<int>("CodigoMarca")
                        .HasColumnType("int")
                        .HasColumnName("Cod_Marca");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Descricao");

                    b.Property<int>("Estoque")
                        .HasColumnType("int")
                        .HasColumnName("Estoque");

                    b.Property<int?>("MarcaModelCodigoMarca")
                        .HasColumnType("int");

                    b.HasKey("Codigo");

                    b.HasIndex("MarcaModelCodigoMarca");

                    b.ToTable("Produtos");
                });

            modelBuilder.Entity("ApiProdutosPessoas.Models.ProdutoModel", b =>
                {
                    b.HasOne("ApiProdutosPessoas.Models.MarcaModel", "Marca")
                        .WithMany()
                        .HasForeignKey("Codigo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiProdutosPessoas.Models.MarcaModel", null)
                        .WithMany("Produtos")
                        .HasForeignKey("MarcaModelCodigoMarca");

                    b.Navigation("Marca");
                });

            modelBuilder.Entity("ApiProdutosPessoas.Models.MarcaModel", b =>
                {
                    b.Navigation("Produtos");
                });
#pragma warning restore 612, 618
        }
    }
}
